# Generated by Django 4.2.6 on 2024-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField()),
            ],
        ),
    ]
