# Generated by Django 4.2.6 on 2024-03-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
