# Generated by Django 4.2.6 on 2024-03-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranetApp', '0002_data_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
