# Generated by Django 4.2.6 on 2024-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('academic_rank', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('g_scholar', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='members/')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
