# Generated by Django 4.2.6 on 2024-03-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='academic_rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
