# Generated by Django 4.2.6 on 2024-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='puesto',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
